### ISSUE TITLE
How to submit the prediction files on testing sets?

### ISSUE THREAD

**Issue by cardwing** [karstenBehrendt/unsupervised_llamas#1]
@karstenBehrendt Thanks for your efforts to release the LLAMAS dataset. It will contribute a lot to the research community in autonomous driving fields. However, I wonder how I can submit the prediction files on testing sets. I did not find any button that can support the submission. Thanks in advance.

**Comment by karstenBehrendt** [comment]
This is a duplicate issue, please view the original one [here](https://github.com/karstenBehrendt/benchmarks_website/issues/1)

**Comment by cardwing** [comment]
Thanks.
