### ISSUE TITLE
How to implement the correction method in chapter 3.2 of the paper？

### ISSUE THREAD

**Issue by WangShengjian** [karstenBehrendt/unsupervised_llamas#14]
Thanks for this nice work！
I studied the code in the project, but I did not find a script that implemented the correction process in section 3.2 of the paper.
I don't know how to make Fig. 3(a) to (b) in code
Is this a trade secret? Or  just didn't find the right place of the script?

**Comment by karstenBehrendt** [comment]
The correction is described in the second paragraph in section 3.2 

We used an extremely crude method that was easy to implement and simple to run.
You basically have 6 degrees of freedom. Translation x, y, z and rotation phi, gamma, kappa. We pretty much just sampled a linearly spaced grid of 100000 changes to those values and checked which ones match our detections the best in the image space. 

A smarter option would have been an actual optimization / search but the end result would likely be similar.

**Comment by WangShengjian** [comment]
This concise method is nice！
Thanks for the answer.
