### ISSUE TITLE
Where can I get the simple_baseline checkPoint？

### ISSUE THREAD

**Issue by xuzhuang1996** [karstenBehrendt/unsupervised_llamas#16]
Hi，
Where can I get the simple_baseline checkPoint？
I want to get the result as your [youtube](https://youtu.be/kp0qz8PuXxA) show
Thank you!

**Comment by karstenBehrendt** [comment]
Hi, unfortunately, I was not allowed to publish that. It should be fairly straightforward (and cheap, electricity bill wise) to reproduce a similar baseline. Sorry about that.
