### ISSUE TITLE
Could you tell me what is the world_start's x, y, z world_end's x y z, pixel_start's x y and pixel_end's x y means

### ISSUE THREAD

**Issue by frederichen01** [karstenBehrendt/unsupervised_llamas#17]
Hello, Could you tell me what is the world_start's x, y, z world_end's x y z, pixel_start's x y and pixel_end's x y means?

**Comment by karstenBehrendt** [comment]
The world coordinate x, y, z is a 3d coordinate in meters relative to a map location. I'm not sure what it is relative to at the moment but this is nothing you need to be concerned about unless you really want to dig into this information.

The pixel start and pixel end represent the starting and beginning point within the image. If you draw a line between the two, it'll show a marker in the image.
