### ISSUE TITLE
How to submit the prediction files on testing sets?

### ISSUE THREAD

**Issue by wuyuej** [karstenBehrendt/unsupervised_llamas#19]
Thanks for your wonderful work and high-quality datasets!
I am working on the lane detection task on your dataset, I am about to finish writing a paper recently. I tried to submit on (https://unsupervised-llamas.com/llamas/submission) and email <llamas (at) kbehrendt (dot) com>, but I didn't get a reply. Is there any problem with my submission method? 
Thank you!

**Comment by karstenBehrendt** [comment]
Thanks for letting me know. I had gmail address that would send me those e-mails and google disabled the authentication method I was using. 

In the short-term, please just send your results to the e-mail address listing within my github profile.

Longer-term, I'll try to get that submission system running again. It is a bit unfortunate that this failed silently. Sorry about that.

**Comment by karstenBehrendt** [comment]
Updated the gmail login. Should be fixed. I also saw your submission by e-mail.

**Comment by wuyuej** [comment]
Thank you very much!

**Comment by Stone-flying** [comment]
I tried to submit on (https://unsupervised-llamas.com/llamas/submission) , email <llamas (at) kbehrendt (dot) com>,<[github@kbehrendt.com](mailto:github@kbehrendt.com)>, I didn't get a reply too, Is there any problem with my submission method?  
Thank you!

**Comment by karstenBehrendt** [comment]
The submission worked fine. I was just slow to respond.

**Comment by Stone-flying** [comment]
> The submission worked fine. I was just slow to respond.
Thank you, waiting for your evaluation results.

**Comment by Stone-flying** [comment]
Thank you, waiting for your evaluation results.
