### ISSUE TITLE
labels format issue 

### ISSUE THREAD

**Issue by lordfarquad3211** [karstenBehrendt/unsupervised_llamas#20]
i am trying to train the dataset on YOLOv7 instance segmentation ,although the labels are in json ,they are not in line with yolo annotation arrangement , is there any way i can obtain the labels in yolo arrangement format ?

**Comment by karstenBehrendt** [comment]
Hi- unfortunately, there are thousands of different frameworks so that we won't be able to support all of them. Feel free to write a script to convert the format and create a pull request
