### ISSUE TITLE
Camera intrinsics and extrinsics

### ISSUE THREAD

**Issue by ShanWang-Shan** [karstenBehrendt/unsupervised_llamas#21]
Thank you for your sharing.

May I know the camera's intrinsic information? I found the following answer in the closed issues:
>The camera specs are here https://cds.bosch.us/themes/bosch_cross/amc_pdfs/MPC2_Multi_purpose_camera_292000P0ZK_EN_low.pdf
However, I failed to open the link.
I also wonder if there is information about the extrinsic parameters of each frame. Even if it is not strictly accurate, it is helpful.

Thank you for your time and help.
Best,
Shan

**Comment by karstenBehrendt** [comment]
Hi Shan, I'm sorry but I do not have the camera extrinsics or intrinsics anymore
