### ISSUE TITLE
Odometry?

### ISSUE THREAD

**Issue by sharkybe** [karstenBehrendt/unsupervised_llamas#5]
Hi,
It can be very useful if you can provide the odometry data in some format. 
maybe a 4x4 transformation matrix representing the pose of the camera in every frame w.r.t first frame. 

Thankyou!

**Comment by zhangjy2008327** [comment]
how to calculate mAP from {'recall': corner_recall, 'precision': corner_precision,
            'threshold': corner_threshold, 'auc': auc_value}?

**Comment by zhangjy2008327** [comment]
how to calculate mAP from {'recall': corner_recall, 'precision': corner_precision,
            'threshold': corner_threshold, 'auc': auc_value}?

**Comment by karstenBehrendt** [comment]
Sorry about the response over half a year later. I didn't have my notifications turned on.

@sharkybe There are transformation matrices available for all frames. Feel free to submit a PR with your preferred format
@zhangjy2008327 We use the area under curve (auc) for precision recall values as mAP
