### ISSUE TITLE
how to calculate 0.635(mAP) in MULTI-CLASS LANE MARKER SEGMENTATION

### ISSUE THREAD

**Issue by zhangjy2008327** [karstenBehrendt/unsupervised_llamas#6]
how to calculate 0.635(mAP) and  ap BG | ap L1 | ap L0 | ap R0 | ap R1 in MULTI-CLASS LANE MARKER SEGMENTATION?

**Comment by karstenBehrendt** [comment]
@zhangjy2008327 
You calculate the mean of the area under curve (AUC) for l1, l0, r0, and r1.
